### ISSUE TITLE
Switch from timeout to pipes

### ISSUE THREAD

**Issue by Noitidart** [Noitidart/jscFileWatcher#18]
We should make like a pipe file which is a directory. Make the file watchers watch this pipe directory. Initial idea: On delete it should abort the poll and break the loop. On rename of the file it should abort poll but re-run loop.

**Comment by P0lip** [comment]
**Windows**
[Using Pipes](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365799%28v=vs.85%29.aspx)

**Linux**
We can use [mkfifo()](http://linux.die.net/man/3/mkfifo) method (it creates a file, though, so not sure whether we will use it - we may just use [pipe()](http://linux.die.net/man/2/pipe)). Then we can "read" the stuff using [read()](http://linux.die.net/man/3/read) method like we do in our code, passing this named pipe as the first argument. To manipulate the fifo we can use [fcntl()](http://linux.die.net/man/2/fcntl) method. There may be a need for [fork()](http://linux.die.net/man/2/fork) method.

**OSX, *BSD**
Looks like we can use the same methods and approch as for Linux.

**Comment by tofutim** [comment]
Any progress on getting this to work? Looks like it could theoretically be done without having to make your own c++.

**Comment by Noitidart** [comment]
Thanks @tofutim for the reply! Yes it can super easily be done, I just got distracted with a bunch of other projects. :(

If you can set up the pipes I could definitely hook it up very easily. :)

But I need to work on the pipes for all the OS'es. If you have time I would super appreciate a PR!

**Comment by tofutim** [comment]
probably unix domain sockets for OSX and Unix. Watch out for

http://idletechnology.blogspot.com/2011/12/unix-domain-sockets-on-osx.html

I'll think about it after Thanksgiving. A good one to you.

Cheers,
Tim

**Comment by Noitidart** [comment]
Thanks @tofutim - happy thanksgiving to you too :)

Yeah man if you can just write up a working example in C/C++/C# I can port it to js-ctypes within an hour. Please let me know if you do.

**Comment by Noitidart** [comment]
Landed
