### ISSUE TITLE
did you ever figure out how to use pipes?

### ISSUE THREAD

**Issue by tofutim** [Noitidart/jscFileWatcher#21]
from your post in Oct? https://discourse.mozilla-community.org/t/webextensions-access-to-native-apis-applications/4588

I need to convert an old Xul app to jpm, but it talks to C# using named pipes.

**Comment by Noitidart** [comment]
I never got a chance to work on it. But pipes is not hard to figure it out, just need some time to work on it. If you can just write up the code in C# or C or C++ I can do the port to js-ctypes. :)

**Comment by Noitidart** [comment]
Also you might consider using child_process - https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/system_child_process

That is js-ctypes, it uses subprocess.jsm - https://github.com/Noitidart/subprocess.jsm

**Comment by Noitidart** [comment]
It turned out that pipes was not what I needed, I used a `event` object - http://stackoverflow.com/questions/38386964/createnamedpipe-and-waitformultipleobjectsex

**Comment by Noitidart** [comment]
pipes implemented
